name: flutter_quest
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.6
  responsive_builder: ^0.7.0
  flutter_svg: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/axisHorizontal.svg
    - assets/axisVertical.svg
    - assets/bounceIn.svg
    - assets/bounceInOut.svg
    - assets/bounceOut.svg
    - assets/curveEaseIn.svg
    - assets/curveEaseInOut.svg
    - assets/curveEaseOut.svg
    - assets/curveFastOutEaseIn.svg
    - assets/curveLinear.svg
    - assets/elasticIn.svg
    - assets/elasticInOut.svg
    - assets/elasticOut.svg
